#!/bin/sh

rm -rf repo1 repo2
mkdir repo1 repo2

(
	echo "=== repo1 ==="
	cd repo1
	git init
	git config receive.denyCurrentBranch ignore
	cat >> .git/hooks/post-receive <<-EOF
	#!/bin/sh

	../../../runtime/bin/python ../../../gitblogger/gitblogger.py
	EOF

	chmod 755 .git/hooks/post-receive
)

cat conf >> repo1/.git/config
cp post1.rst repo2/

(
	echo "=== repo2 ==="
	cd repo2
	git init
	git remote add origin ../repo1

	git add post1.rst
	git ci -m 'initial commit'
	git push origin master
)

cp post2.rst repo2/post1.rst

(
	cd repo2
	git ci -m 'revised post1' post1.rst
	git push
)
